CREATE TABLE public."CLASS"
(
    "CLASS_ID" serial NOT NULL,
    "SUBJ_ID" serial NOT NULL,
    CONSTRAINT "CLASS_pkey" PRIMARY KEY ("CLASS_ID"),
    CONSTRAINT "CLASS_FOREIGN_CONSTRAINT" FOREIGN KEY ("SUBJ_ID")
        REFERENCES public."SUBJECT" ("SUBJ_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public."SUBJ_TEACHER"
(
    "CLASS_ID" serial NOT NULL,
    "TEACHER_ID" serial NOT NULL,
    CONSTRAINT "SUBJECT_FOREIGN_CONSTRAINT" FOREIGN KEY ("CLASS_ID")
        REFERENCES public."CLASS" ("CLASS_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "TEACHER_FOREIGN_CONSTRAINT" FOREIGN KEY ("TEACHER_ID")
        REFERENCES public."TEACHER" ("TEACHER_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public."ENROLLED_STUDENTS"
(
    "ENROLLED_ID" serial NOT NULL,
    "STUD_ID" serial NOT NULL,
    "SUBJ_ID" serial NOT NULL,
    CONSTRAINT "ENROLLED_STUDENTS_pkey" PRIMARY KEY ("ENROLLED_ID"),
    CONSTRAINT "STUDENT_FOREIGN_CONSTRAINT" FOREIGN KEY ("STUD_ID")
        REFERENCES public."STUDENT" ("STUD_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "SUBJECT_FOREIGN_CONSTRAINT" FOREIGN KEY ("SUBJ_ID")
        REFERENCES public."SUBJECT" ("SUBJ_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public."TIMETABLE"
(
    "DATE_ID"serial NOT NULL,
    "DATE" timestamp NOT NULL,
    "CLASS_ID" serial NOT NULL,
    CONSTRAINT "TIMETABLE_pkey" PRIMARY KEY ("DATE_ID"),
    CONSTRAINT "CLASS_FOREIGN_CONSTRAINT" FOREIGN KEY ("CLASS_ID")
        REFERENCES public."CLASS" ("CLASS_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public."MARKS"
(
    "MARK_ID" serial NOT NULL,
    "ENROLLED_ID" serial NOT NULL,
    "DATE_ID" serial NOT NULL,
    "MARK" integer NOT NULL,
    "ATTENDING" boolean,
    CONSTRAINT "MARKS_pkey" PRIMARY KEY ("MARK_ID"),
    CONSTRAINT "TIMETABLE_FOREIGN_CONSTRAINT" FOREIGN KEY ("DATE_ID")
        REFERENCES public."TIMETABLE" ("DATE_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "ENROLLED_STUDENTS_FOREIGN_CONSTRAINT" FOREIGN KEY ("ENROLLED_ID")
        REFERENCES public."ENROLLED_STUDENTS" ("ENROLLED_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
