CREATE TABLE public."CLASS"
(
    "CLASS_ID" integer NOT NULL,
    "SUBJ_ID" integer NOT NULL,
    CONSTRAINT "CLASS_pkey" PRIMARY KEY ("CLASS_ID"),
    CONSTRAINT "CLASS_FOREIGN_CONSTRAINT" FOREIGN KEY ("SUBJ_ID")
        REFERENCES public."SUBJECT" ("SUBJ_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public."SUBJ_TEACHER"
(
    "SUBJ_ID" integer NOT NULL,
    "TEACHER_ID" integer NOT NULL,
    CONSTRAINT "SUBJECT_FOREIGN_CONSTRAINT" FOREIGN KEY ("SUBJ_ID")
        REFERENCES public."SUBJECT" ("SUBJ_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "TEACHER_FOREIGN_CONSTRAINT" FOREIGN KEY ("TEACHER_ID")
        REFERENCES public."TEACHER" ("TEACHER_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public."ENROLLED_STUDENTS"
(
    "STUD_ID" integer NOT NULL,
    "SUBJ_ID" integer NOT NULL,
    CONSTRAINT "STUDENT_FOREIGN_CONSTRAINT" FOREIGN KEY ("STUD_ID")
        REFERENCES public."STUDENT" ("STUD_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "SUBJECT_FOREIGN_CONSTRAINT" FOREIGN KEY ("SUBJ_ID")
        REFERENCES public."SUBJECT" ("SUBJ_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public."MARKS"
(
    "MARK_ID" integer NOT NULL,
    "STUD_ID" integer NOT NULL,
    "CLASS_ID" integer NOT NULL,
    "MARK" integer NOT NULL,
    "ATTENDING" boolean,
    CONSTRAINT "MARKS_pkey" PRIMARY KEY ("MARK_ID"),
    CONSTRAINT "CLASS_FOREIGN_CONSTRAINT" FOREIGN KEY ("CLASS_ID")
        REFERENCES public."CLASS" ("CLASS_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "STUD_FOREIGN_CONSTRAINT" FOREIGN KEY ("STUD_ID")
        REFERENCES public."STUDENT" ("STUD_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public."TIMETABLE"
(
    "DATE" date NOT NULL,
    "CLASS_ID" integer NOT NULL,
    CONSTRAINT "TIMETABLE_pkey" PRIMARY KEY ("DATE"),
    CONSTRAINT "CLASS_FOREIGN_CONSTRAINT" FOREIGN KEY ("CLASS_ID")
        REFERENCES public."CLASS" ("CLASS_ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);